drop table Person;

CREATE TABLE IF NOT EXISTS Person (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      username varchar(100) NOT NULL,
    year_of_birth int NOT NULL,
    password varchar NOT NULL,
    CONSTRAINT pk_person PRIMARY KEY (id)
    );

CREATE UNIQUE INDEX IF NOT EXISTS username_index ON Person(username);
